services:
  frontend:
    container_name: frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_USER_SERVICE_URL: http://localhost:8080
        NEXT_PUBLIC_AUTH_SERVICE_URL: http://localhost:8081
        NEXT_PUBLIC_EVENT_SERVICE_URL: http://localhost:8082
        NEXT_PUBLIC_BOOKING_SERVICE_URL: http://localhost:8083
    depends_on:
      - user-service
      - event-service
      - booking-service
    ports:
      - "3000:3000"

  user-service:
    container_name: user-service
    restart: unless-stopped
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
      - "9090:9090"

  auth-service:
    container_name: auth-service
    restart: unless-stopped
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8081:8080"
      - "9091:9090"

  event-service:
    container_name: event-service
    restart: unless-stopped
    build:
      context: ./services/event-service
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8082:8080"
      - "9092:9090"

  booking-service:
    container_name: booking-service
    restart: unless-stopped
    build:
      context: ./services/booking-service
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8083:8080"
      - "9093:9090"

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
