services:

  configsvr3:
    container_name: configsvr3
    image: mongo:latest
    command: mongod --configsvr --replSet config_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 10003:27017
    volumes:
      - configsvr3:/data/db

  shardsvr1_3:
    container_name: shardsvr1_3
    image: mongo:latest
    command: mongod --shardsvr --replSet shard1_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 20003:27017
    volumes:
      - shardsvr1_3:/data/db

  shardsvr2_3:
    container_name: shardsvr2_3
    image: mongo:latest
    command: mongod --shardsvr --replSet shard2_rs --dbpath /data/db --port 27017 --bind_ip_all
    ports:
      - 20006:27017
    volumes:
      - shardsvr2_3:/data/db

volumes:
  configsvr3:
  shardsvr1_3:
  shardsvr2_3: